import Head from 'next/head'
import { Navbar, Sidebar, Content } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Labexperiments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar />
      <Content />
    </div>
  )
}
